services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: ${KEYCLOAK_COMMAND:-start}
    environment:
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - keycloak_network
    volumes:
      - ./themes:/opt/keycloak/themes
      - ./providers:/opt/keycloak/providers/

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge